name: CI Branch - Le Journal
on:
  push:
    branches:
      - '**'
      - '!main'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: |
          bun install
          bun run lint
